#+title: speedrect - Changelog
#+author: J.D. Smith
#+language: en

* v0.7 (2024-12-17)

- Added demo movie.
- Automatically recall stashed rectangle when multiple cursors mode (=M=) completes.
- Stash rectangle prior to quitting.
- Optionally preserve space on kill (=k=) when called with prefix (i.e. copy then clear).
- When rectangle filling text, if the selected rectangle is entirely blank, use the contents of the last killed rectangle.  This makes possible a two-step process for rectangle filling:
  1. kill/copy a rectangle
  2. mark a blank rectangular "target" region, and yank-fill to that width.
- Other minor rectangle fill improvements to add stability.
- New decrement/increment commands (=-= / =+=) for adding/subtracting to first numeric column (numeric prefix allowed).
- Alignment-preserving white-space deletion, for left (default) or right (with prefix) justification of column.
- New undo command (=u=) to undo last action, preserving the selected rectangle.
- =[BUGFIX]= Avoid rare alignment issues when using ~yank-from-calc~ (=m=).

* v0.6 (2024-12-07)

- Published on ELPA.
- Added ~copy-rectangle-as-text~ to put yankable lines of text on the kill ring.
- Permit mismatched calc matrix and selected rectangle row length.
- =BUGFIX= correctly save rectangle position after ~delete-rest~.

* v0.5.2 (2024-12-03)

- Improved rectangle shift off ends of lines.
- Better calc integration and formatting.
- Vector shortening and brackets now always ignored.

* v0.5

- New command =f= to fill (wrap) text in the rectangle. Uses prefix for fill width (defaults to rectangle width).

* v0.4

- New command =x= for moving around rectangle corners.
- New command =M= for placing multiple-cursors on each line at the current column.
